<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">日付時刻フォーマット変換ツール</h2>
        <div class="card-body">
            <p>入力した日付文字列を様々な形式に変換するツールです。</p>

            <a class="btn btn-primary" href="/date"> &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">時刻差分算出ツール</h2>
        <div class="card-body">
            <p>2つの時刻から差分の、秒・分・時間・日数を算出します</p>

            <a class="btn btn-primary" href="/date-diff"> &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">パスワードジェネレーター</h2>
        <div class="card-body">
            <p>パスワードを自動で作成します。</p>

            <a class="btn btn-primary" href="/password"> &raquo; </a>
        </div>
    </div>
</div>
