<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4"><?= $this->translate('Date format conversion tool', 'date') ?></h1>
    <hr/>
</div>

<form class="form-inline">
    <div class="form-group">
        <?= $this->formLabel($form->get('q')->setLabelAttributes(['class' => 'ml-2 mb-2'])) ?>
        <?= $this->bs4FormElement($form->get('q')->setAttribute('class', 'form-control ml-2 mb-2')) ?>
        <button type="submit" class="btn btn-primary ml-2 mb-2">Submit</button>
        <?= $this->bs4FormElementErrors($form->get('q')) ?>
    </div>
</form>

<?php if (isset($date)) : ?>
    <table class="table">
        <tbody>
            <?php foreach ($date as $key => $value) : ?>
                <tr>
                    <th><?= $this->escapeHtml($key) ?></th>
                    <td><?= $this->escapeHtml($value) ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
