<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header"><?= $this->translate('Date format converter', 'index') ?></h2>
        <div class="card-body">
            <p>
                <?= $this->translate('Date format converter convert to various date format from input date(time) text.', 'index') ?>
            </p>

            <a class="btn btn-primary" href="/date"> &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= $this->translate('Password generator', 'index') ?></h2>
        <div class="card-body">
            <p>
                <?= $this->translate('Password generator create various password automarically.', 'index') ?>
            </p>

            <a class="btn btn-primary" href="/password"> &raquo; </a>
        </div>
    </div>
</div>
