<?php
use Application\Form\PasswordForm;
?>
<h1><?= $this->translate('Password generator', 'password') ?></h1>
<hr/>
<p>
    <?= $this->translate('Enter the information of password to below form and click submit button, generate password automatically as you like.', 'password') ?>
</p>

<?= $this->form()->openTag($form) ?>
    <div class="form-group">
        <?= $this->formLabel($form->get(PasswordForm::TEXT_NUMBER_OF_CHARACTERS)
            ->setLabel($this->translate('Number of characters', 'password'))
            ->setLabelAttributes(['class' => 'form-label'])) ?>
        <?= $this->bs4FormElement($form->get(PasswordForm::TEXT_NUMBER_OF_CHARACTERS)
            ->setAttribute('class', 'form-control')) ?>
        <?= $this->bs4FormElementErrors($form->get(PasswordForm::TEXT_NUMBER_OF_CHARACTERS)) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get(PasswordForm::TEXT_NUMBER_OF_PASSWORDS)
            ->setLabel($this->translate('Number of passwards to create', 'password'))
            ->setLabelAttributes(['class' => 'form-label'])) ?>
        <?= $this->bs4FormElement($form->get(PasswordForm::TEXT_NUMBER_OF_PASSWORDS)
            ->setAttribute('class', 'form-control')) ?>
        <?= $this->bs4FormElementErrors($form->get(PasswordForm::TEXT_NUMBER_OF_PASSWORDS)) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get(PasswordForm::TEXT_EXCLUDE_CHARACTERS)
            ->setLabel($this->translate('Exclude characters', 'password'))
            ->setLabelAttributes(['class' => 'form-label'])) ?>
        <?= $this->bs4FormElement($form->get(PasswordForm::TEXT_EXCLUDE_CHARACTERS)
            ->setAttribute('class', 'form-control')) ?>
        <?= $this->bs4FormElementErrors($form->get(PasswordForm::TEXT_EXCLUDE_CHARACTERS)) ?>
    </div>
    <div class="form-group form-check">
        <?= $this->bs4FormElement($form->get(PasswordForm::CHECKBOX_IS_DISALLOW_SAME_CHARACTER)
            ->setAttribute('class', 'form-check-input')
            ->setAttribute('id', PasswordForm::CHECKBOX_IS_DISALLOW_SAME_CHARACTER)) ?>
        <?= $this->formLabel($form->get(PasswordForm::CHECKBOX_IS_DISALLOW_SAME_CHARACTER)
            ->setLabel($this->translate('Do not use same charactor', 'password'))
            ->setLabelAttributes(['class' => 'form-check-label'])) ?>
    </div>
    <button type="submit" class="btn btn-primary mb-2"><?= $this->translate('Submit', 'date') ?></button>
<?= $this->form()->closeTag() ?>

<?php if (isset($password)) : ?>
    <div class="form-group">
        <label><?= $this->translate('Use printing characters, excluding space.', 'password') ?></label>
        <textarea readonly
            class="form-control"
            rows="<?= count($password['graph']) ?>"
        ><?= $this->escapeHtml(implode("\n", $password['graph'])) ?></textarea>
        <label><?= $this->translate('Use alphabet and digits.', 'password') ?></label>
        <textarea readonly
            class="form-control"
            rows="<?= count($password['alnum']) ?>"
        ><?= $this->escapeHtml(implode("\n", $password['alnum'])) ?></textarea>
        <label><?= $this->translate('Use alphabet only.', 'password') ?></label>
        <textarea readonly
            class="form-control"
            rows="<?= count($password['alpha']) ?>"
        ><?= $this->escapeHtml(implode("\n", $password['alpha'])) ?></textarea>
    </div>
<?php endif ?>
